# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2358b22f44777c603cada8b829446b425a628a47f0502a6da22b31c53ac47bd05fded7d2b764a35202eb51403a4bf05e4076b7ba7499793d39c831585dc83018

test:
  secret_key_base: f56b180b7503b020970a0cf02879e43d3d9f0fc341c2b0aa488b18ec0f39263ac80772bd47b3021129310ee02e1d0bb8c0dfb578cfe73243aa0c93bf15adcd45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
